name: 'Pull JAR'
inputs:
  github-token:
    description: 'The GitHub token to use'
    required: true

description: 'Pulling a JAR from GitHub packages'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20


    - name: Setup Java 17 Temurin
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'


    - name: Pull package to GitHub Packages
      uses: nvoxland/jar-download-action@v1
      with:
          groupId: com.example
          artifactId: testino
          version: 0.0.1-SNAPSHOT
          outputDirectory: app_libs
          repository: https://maven.pkg.github.com/Reny24/TestingAction/packages/com/example/testino/0.0.1-SNAPSHOT
    #  run: ls -l app_libs
    #  run: |
     #    curl -L -O -H "Authorization: Bearer ${{ inputs.github-token }}" https://maven.pkg.github.com/Reny24/TestingAction/packages/com/example/testino/0.0.1-SNAPSHOT/testino-0.0.1-20240408.085253-1.jar
    #  shell: bash
    #  env:
     #   GITHUB_TOKEN: steps.create_token.outputs.token

