name: 'Pull JAR'
inputs:
  github-token:
    description: 'The GitHub token to use'
    required: true

description: 'Pulling a JAR from GitHub packages'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: In testino
      run: cd testino
      shell: bash

    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.9.5

    - name: Setup Java 17 Temurin
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'


 #   - name: Pull package to GitHub Packages
     # uses: nvoxland/jar-download-action@v1
     # with:
      #    groupId: com.example
       #   artifactId: testino
        #  version: 0.0.1-SNAPSHOT
       #   outputDirectory: app_libs
      #    repository: https://maven.pkg.github.com/Reny24/TestingAction/packages/com/example/testino/0.0.1-SNAPSHOT
    #  env:
     #   JAVA_HOME: 'C:\Program Files\Java\jdk-17'
    #  run: ls -l app_libs


   #   run: |
   #      curl -L -O -H "Authorization: Bearer ${{ inputs.github-token }}" https://maven.pkg.github.com/Reny24/TestingAction/packages/com/example/testino/0.0.1-SNAPSHOT
   #   shell: bash

    - name: take last version
      shell: bash

      run:
         mvn dependency:copy --file /testino \
            -Dartifact=com.example:testino:0.0.1-SNAPSHOT \
            -DoutputDirectory=/tmp/my_custom_dir \
            -DremoteRepositories=https://maven.pkg.github.com/Reny24/TestingAction \
      env:
        GITHUB_ACTOR: ghs
        GITHUB_TOKEN: ${{ inputs.github-token }}
    #  env:
     #   GITHUB_TOKEN: steps.create_token.outputs.token

