name: 'Push JAR'
inputs:
  github-token:
    description: 'The GitHub token to use'
    required: true

description: 'Pushing a JAR in GitHub packages'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20



    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.9.5


    - name: Setup Java 17 Temurin
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'



    - name: Creazione package mvn
      shell: bash
      run: |
        mvn package --file ./testino/pom.xml
        

    - name: Trova pacchetto jar
      shell: bash
      run: find ./testino/target -name "*.jar" -type f


  #  - uses: s4u/maven-settings-action@v3.0.0
   #   with:
    #    servers: '[{ "id": "github", "username": "ghs", "password": "${{ env.GITHUB_TOKEN }}" }]'
     # env:
      #  GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}


    - name: Push package to GitHub Packages
      shell: bash

      run: curl -X PUT -u ghs:${{ env.GITHUB_TOKEN }} --data-binary @testino/target/testino-0.0.1-SNAPSHOT.jar "https://maven.pkg.github.com/Reny24/TestingAction/com/example/testino/0.0.1-SNAPSHOT/testino-0.0.1-SNAPSHOT.jar"

  #    run: mvn deploy -X --file  testino/pom.xml
      env:
        GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
