name: Docker Image CI

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - main1
jobs:
  build-and-push:
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}

    steps:

      - name: Generate Token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - uses: actions/checkout@v3
    #  - name: Login to GitHub Packages Docker registry
     #   run: echo "${{ steps.generate_token.outputs.token }}" | docker login ghcr.io -u ghs --password-stdin
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ghs
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Inside the testino
        run: cd testino


      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}


   #   - name: Build the Docker image
   #     run: docker build . --file testino/Dockerfile --tag maven:3.8.4-openjdk-17-slim

   #   - name: Push the Docker image to GitHub Packages
   #     run: docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}:latest
      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
