name: Publish/Push Artifact Package by Auth Github App
on: workflow_dispatch
jobs:
  microservice-test:

    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Generate Token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          installation_retrieval_mode: id
          installation_retrieval_payload: ${{ secret.INSTALLATION_ID }}
          

      - run: "echo 'The created token is masked: ${{ steps.create_token.outputs.token }}'"
      #Setup Maven, act usa un Container Docker quindi bisogna rifare il setup al suo interno
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.9.5

      # Ubuntu-latest usa maven 3.8.8 / Controllare se la versione usata nel Runner e Java 21
      - name: Setup Java 17 Temurin
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Per default qui andra' a controllare direttamente la repo dove e' attaccato questo workflow
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Creazione package mvn
        run: | 
          mvn package
      - name: Trova pacchetto jar
        run: find ./target -name "*.jar" -type f


      - name: publish
        run: curl -X PUT -u Reny24:${{ steps.generate_token.outputs.token }} --data-binary ./target/micro-services-test1-0.0.1-SNAPSHOT.jar "https://maven.pkg.github.com/Reny24/TestingAction"
