name: Docker Image CI

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - main1

jobs:
  build-and-push:
    if: github.event.pull_request.merged == true
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Authenticate with JFrog Artifactory
        run: echo "${{ secrets.JFROG_PASSWORD }}" | docker login -u "${{ secrets.JFROG_USER }}" --password-stdin http://localhost:8082/artifactory/example-repo-local

      - name: Build and push Docker image
        run: |
          docker build -t localhost:8082/artifactory/example-repo-local/reny24/testingaction:latest .
          docker push localhost:8082/artifactory/example-repo-local/reny24/testingaction:latest
