name: Publish/Push Artifact Package by Auth Github App
on: workflow_dispatch
jobs:
  microservice-test:

    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Generate Token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
        #  installation_id: ${{ secrets.INSTALLATION_ID }}
   #   - uses: actions/create-github-app-token@v1.9.2
   #     id: app-token
   #     with:
    #      app-id: ${{ secrets.APP_ID }}
     #     private-key: ${{ secrets.PRIVATE_KEY }}
          

      - run: "echo 'The created token is masked: ${{ steps.create_token.outputs.token }}'"
     


  
      - name: Checkout the code
        uses: actions/checkout@v4

      - uses: s4u/maven-settings-action@v3.0.0
        with:
          repositories: '[{ "url": "https://maven.pkg.github.com/Reny24/TestingAction/packages/com/example/testino/0.0.1-SNAPSHOT/testino-0.0.1-20240408.085253-1.jar"}]'
          servers: '[{ "id": "github", "username": "ghs", "password": "${{ secrets.GITHUB_TOKEN }}" }]'
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}



      
      - name: Pull package to GitHub Packages
       # run: |
        #  curl -L -O -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://maven.pkg.github.com/Reny24/TestingAction/packages/com/example/testino/0.0.1-SNAPSHOT/testino-0.0.1-20240408.085253-1.jar
       # env:
        #   GITHUB_TOKEN: steps.create_token.outputs.token
        run: mvn install -s 

        
      - name: Find package jar
        run: find . -name "*.jar" -type f
     #   uses:  actions/download-artifact@v4 
      #  with: 
       #    name: com.example.testino
           
      # - name: Display structure of downloaded files
       # run: ls -R
           
          
