name: Trigger a workflow in another repo
on: workflow_dispatch
jobs:
  microservice-test:

    permissions:
      actions: write
    runs-on: ubuntu-latest
    steps:

     - name: Generate Token
       uses: actions/create-github-app-token@v1.9.2
       id: app-token
       with:
         app-id: ${{ secrets.APP_ID }}
         private-key: ${{ secrets.PRIVATE_KEY }}

     - name: Repository Dispatch
   #    uses: peter-evans/repository-dispatch@v3
   #    with:
   #       token: ${{ env.GITHUB_TOKEN }}
   #       repository: Reny24/TestingJen
   #       event-type: workflow_run
       run: |
        curl -L \
        -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: Bearer ${{ env.GITHUB_TOKEN }}" \
         https://api.github.com/repos/Reny24/TestingJen/actions/workflows/92409550/dispatches \
         -d '{"ref":"master"}'
       env:
         GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}